import Header from "@/components/Header";
import Footer from "@/components/Footer";
import FloatingContact from "@/components/FloatingContact";
import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import { Building2, Users, Globe, Clock, CheckCircle, Plane, Hotel, CalendarCheck, Headphones, Shield, BarChart3, Award, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import corporateHero from "@/assets/corporate-hero.jpg";
import { useLanguage } from "@/contexts/LanguageContext";

const AnimatedSection = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });
  return <motion.div ref={ref} initial={{ opacity: 0, y: 30 }} animate={isInView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.6 }} className={className}>{children}</motion.div>;
};

const CorporatePage = () => {
  const { t } = useLanguage();
  const services = [
    { icon: Plane, title: t("حجوزات الطيران", "Flight Bookings"), description: t("إدارة شاملة لحجوزات الطيران مع أفضل الأسعار والمرونة في التعديل والإلغاء", "Comprehensive flight booking management with best prices and flexible modifications") },
    { icon: Hotel, title: t("حجوزات الفنادق", "Hotel Bookings"), description: t("شراكات مع أكبر سلاسل الفنادق العالمية لتوفير أسعار تنافسية خاصة بالشركات", "Partnerships with major hotel chains for competitive corporate rates") },
    { icon: CalendarCheck, title: t("تنظيم المؤتمرات", "Conference Planning"), description: t("تخطيط وتنظيم المؤتمرات والفعاليات التجارية من الألف إلى الياء", "Planning and organizing conferences and business events from A to Z") },
    { icon: Globe, title: t("خدمات التأشيرات", "Visa Services"), description: t("استخراج التأشيرات لجميع الوجهات بسرعة واحترافية عالية", "Visa processing for all destinations quickly and professionally") },
    { icon: Headphones, title: t("دعم على مدار الساعة", "24/7 Support"), description: t("فريق متخصص متاح 24/7 لخدمة موظفي شركتكم أينما كانوا", "Specialized team available 24/7 to serve your employees wherever they are") },
    { icon: BarChart3, title: t("تقارير مفصلة", "Detailed Reports"), description: t("تقارير شهرية وسنوية شاملة لمصاريف السفر مع تحليلات لتوفير التكاليف", "Monthly and annual travel expense reports with cost-saving analysis") },
  ];
  const benefits = [t("أسعار تنافسية خاصة للشركات","Competitive corporate prices"),t("مدير حساب مخصص لشركتكم","Dedicated account manager"),t("تقارير مالية شهرية مفصلة","Detailed monthly financial reports"),t("دعم فني على مدار الساعة","24/7 technical support"),t("مرونة كاملة في الحجز والإلغاء","Full flexibility in booking & cancellation"),t("برنامج ولاء ومكافآت للشركات","Corporate loyalty & rewards program"),t("حلول دفع مرنة ومتعددة","Flexible payment solutions"),t("خدمات VIP للمسؤولين التنفيذيين","VIP services for executives")];
  const stats = [{icon:Building2,value:"+100",label:t("شركة شريكة","Partner Companies")},{icon:Users,value:"+5,000",label:t("موظف مسافر سنوياً","Employees Traveling Yearly")},{icon:Globe,value:"+50",label:t("وجهة عمل","Business Destinations")},{icon:Clock,value:"24/7",label:t("دعم متواصل","Continuous Support")}];

  return (
    <div className="min-h-screen">
      <Header /><FloatingContact />
      <section className="relative pt-32 pb-24 overflow-hidden min-h-[500px] flex items-center">
        <div className="absolute inset-0"><img src={corporateHero} alt="" className="w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-l from-black/85 via-black/70 to-black/50" /></div>
        <div className="container-custom relative z-10">
          <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:0.6}} className="max-w-2xl">
            <span className="inline-flex items-center gap-2 text-secondary font-medium mb-4 bg-secondary/10 backdrop-blur-sm px-4 py-2 rounded-full"><Building2 size={18} />{t("قطاع الشركات","Corporate Sector")}</span>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-6 leading-tight">{t("شريكك المثالي في","Your Ideal Partner in")}<span className="text-secondary">{t(" عالم السفر"," the World of Travel")}</span> {t("والاستكشاف","& Discovery")}</h1>
            <p className="text-lg text-white/80 leading-relaxed mb-8">{t("نحن ملتزمون بتقديم تجربة سفر استثنائية، مدعومة بخدمة عملاء متميزة وحلول مبتكرة تلبي كافة احتياجات شركتكم","We are committed to delivering an exceptional travel experience, supported by outstanding customer service and innovative solutions for all your company's needs")}</p>
            <div className="flex gap-4 flex-wrap">
              <a href="https://wa.me/966534817876?text=مرحباً، أرغب في التواصل مع قسم الشركات" target="_blank" rel="noopener noreferrer"><Button className="btn-secondary rounded-xl px-8 py-6 text-base gap-2">{t("تواصل مع قسم الشركات","Contact Corporate Dept")}<ArrowLeft size={18} /></Button></a>
              <a href="tel:+966112200396"><Button variant="outline" className="rounded-xl px-8 py-6 text-base border-white/30 text-white bg-white/10 hover:bg-white/20">{t("اتصل بنا","Call Us")}</Button></a>
            </div>
          </motion.div>
        </div>
      </section>
      <section className="py-12 bg-card border-b border-border"><div className="container-custom"><div className="grid grid-cols-2 md:grid-cols-4 gap-6">{stats.map((stat,i)=>(<motion.div key={stat.label} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:i*0.1}} className="text-center"><stat.icon className="mx-auto mb-3 text-primary" size={32}/><p className="text-3xl font-bold text-foreground">{stat.value}</p><p className="text-sm text-muted-foreground mt-1">{stat.label}</p></motion.div>))}</div></div></section>
      <section className="section-padding bg-background"><div className="container-custom"><AnimatedSection className="text-center mb-12"><h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">{t("خدماتنا ","Our Services ")}<span className="text-primary">{t("للشركات","for Corporates")}</span></h2><p className="text-muted-foreground max-w-2xl mx-auto">{t("نقدم مجموعة شاملة من خدمات السفر المصممة خصيصاً لتلبية احتياجات الشركات والمؤسسات","A comprehensive range of travel services designed to meet corporate needs")}</p></AnimatedSection><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{services.map((service)=>(<AnimatedSection key={service.title}><div className="bg-card border border-border rounded-2xl p-6 h-full hover:shadow-lg hover:border-primary/20 transition-all duration-300 group"><div className="w-14 h-14 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors"><service.icon className="text-primary" size={28}/></div><h3 className="text-lg font-bold text-foreground mb-2">{service.title}</h3><p className="text-muted-foreground text-sm leading-relaxed">{service.description}</p></div></AnimatedSection>))}</div></div></section>
      <section className="section-padding bg-muted/30"><div className="container-custom"><div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center"><AnimatedSection><span className="text-secondary font-medium flex items-center gap-2 mb-2"><Award size={16}/>{t("لماذا تختارنا","Why Choose Us")}</span><h2 className="text-3xl md:text-4xl font-bold text-foreground mb-6">{t("مميزات ","Benefits of ")}<span className="text-primary">{t("الشراكة","Partnership")}</span> {t("معنا","with Us")}</h2><p className="text-muted-foreground leading-relaxed mb-8">{t("نوفر لشركتكم حلول سفر متكاملة تجمع بين الجودة العالية والتكلفة المناسبة مع دعم فني متواصل","We provide integrated travel solutions combining high quality and reasonable cost with continuous support")}</p><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{benefits.map((benefit,i)=>(<motion.div key={benefit} initial={{opacity:0,x:20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*0.08}} className="flex items-center gap-2"><CheckCircle className="text-primary flex-shrink-0" size={18}/><span className="text-foreground text-sm">{benefit}</span></motion.div>))}</div></AnimatedSection><AnimatedSection><div className="grid grid-cols-2 gap-4"><div className="bg-gradient-to-br from-primary to-primary-dark rounded-2xl p-6 text-center text-primary-foreground"><Shield className="mx-auto mb-3" size={32}/><p className="text-2xl font-bold mb-1">+15</p><p className="text-sm opacity-90">{t("عام خبرة","Years Experience")}</p></div><div className="bg-card border border-border rounded-2xl p-6 text-center"><Users className="mx-auto mb-3 text-secondary" size={32}/><p className="text-2xl font-bold text-foreground mb-1">+5,000</p><p className="text-sm text-muted-foreground">{t("موظف سنوياً","Employees Yearly")}</p></div><div className="bg-card border border-border rounded-2xl p-6 text-center"><Globe className="mx-auto mb-3 text-primary" size={32}/><p className="text-2xl font-bold text-foreground mb-1">+50</p><p className="text-sm text-muted-foreground">{t("وجهة عمل","Business Destinations")}</p></div><div className="bg-gradient-to-br from-secondary to-secondary-dark rounded-2xl p-6 text-center text-secondary-foreground"><Headphones className="mx-auto mb-3" size={32}/><p className="text-2xl font-bold mb-1">24/7</p><p className="text-sm opacity-90">{t("دعم متواصل","Continuous Support")}</p></div></div></AnimatedSection></div></div></section>
      <section className="section-padding bg-background"><div className="container-custom"><AnimatedSection className="text-center mb-12"><h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">{t("كيف ","How We ")}<span className="text-primary">{t("نعمل","Work")}</span> {t("معكم","with You")}</h2></AnimatedSection><div className="grid grid-cols-1 md:grid-cols-4 gap-6">{[{step:"01",title:t("التواصل","Contact"),desc:t("تواصلوا معنا لمعرفة احتياجات شركتكم","Reach out to discuss your company's needs")},{step:"02",title:t("الدراسة","Analysis"),desc:t("ندرس متطلباتكم ونصمم خطة مخصصة","We analyze your needs and design a custom plan")},{step:"03",title:t("التنفيذ","Execution"),desc:t("ننفذ الخطة بأعلى معايير الجودة","We execute the plan with highest quality standards")},{step:"04",title:t("المتابعة","Follow-up"),desc:t("نتابع معكم ونقدم تقارير دورية","We follow up and provide periodic reports")}].map((item)=>(<AnimatedSection key={item.step}><div className="text-center"><div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4"><span className="text-2xl font-bold text-primary">{item.step}</span></div><h3 className="font-bold text-foreground mb-2">{item.title}</h3><p className="text-sm text-muted-foreground">{item.desc}</p></div></AnimatedSection>))}</div></div></section>
      <section className="py-16 bg-gradient-to-l from-primary to-primary-dark text-primary-foreground"><div className="container-custom text-center"><h2 className="text-3xl font-bold mb-4">{t("ابدأ شراكتك معنا اليوم","Start Your Partnership Today")}</h2><p className="text-primary-foreground/80 mb-8 max-w-xl mx-auto">{t("انضم لأكثر من 100 شركة تثق بنا لإدارة رحلات عملها","Join over 100 companies that trust us to manage their business travel")}</p><div className="flex gap-4 justify-center flex-wrap"><a href="https://wa.me/966534817876?text=مرحباً، أرغب في التواصل مع قسم الشركات" target="_blank" rel="noopener noreferrer"><Button className="btn-secondary rounded-xl px-8">{t("تواصل عبر واتساب","WhatsApp Us")}</Button></a><Link to="/contact"><Button variant="outline" className="rounded-xl px-8 border-white/30 text-white bg-white/10 hover:bg-white/20">{t("طلب عرض أسعار","Request a Quote")}</Button></Link></div></div></section>
      <Footer />
    </div>
  );
};
export default CorporatePage;
